# Generated by Django 3.2.12 on 2022-12-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_updateorder_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
